telegram_homepage:
    path: /telegramBot
    defaults: { _controller: TelegramBundle:Default:index }

bot_try:
    path: /telegramBot/tryBot
    defaults: {_controller: TelegramBundle:Bot:tryBot }

webhook:
    path: /telegramBot/webhook/{code}
    defaults: {_controller: TelegramBundle:Bot:webhook }

clear:
    path: /telegramBot/clear/{code}
    defaults: {_controller: TelegramBundle:Bot:clear }