# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    weather_helper:
        class: Miguelgm\TelegramBundle\Services\WeatherHelper
        arguments: ["%open_weather_api%"]

    email_helper:
        class: AppBundle\Services\EmailHelper
        arguments: ["@mailer"]

